spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/restock
    username: root
    password: 
    validationQuery: SELECT 1
    driver-class-name: org.mariadb.jdbc.Driver
    tomcat:
          max-active: 2
          min-idle: 1
          initial-size: 2
          max-idle: 2
          test-on-borrow: true
          validation-query: SELECT 1
          test-while-idle: true